#!/usr/bin/env bash                                                           
# Install and configure HAproxy on your lb-01 server                          
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  wisegreen-frontend
        bind *:80
        mode http
        default_backend ehoneah-backend
backend wisegreen-backend
        balance roundrobin
        server 63210-web-01 100.25.48.138:80 check
        server 63210-web-02 54.90.26.216.85:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
