#!/usr/bin/env bash
"""Pings an IP address which passed as an argument"""
 #pings an IP address passed as an argument
if [ "$1" == "" ]; 
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi
