#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
file_h="bestschool"

if [ -e "$file_h" ]
then

    echo "bestschool file exists"
    if [ -s "$file_h" ]
    then
        echo "bestschool file is not empty"
    else
        echo "bestschool file is empty"
    fi

    if [ -f "$file_h" ]
    then
        echo "bestschool is a regular file"
    fi
else
    echo "bestschool file does not exist"
fi